sudo: required
language: java
install: true

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t existmaser/restaurant-rest .

script:
  - echo "testing.."
  - chmod +x ./gradlew
  - ./gradlew test

after_success:
  - echo "Test Success"

deploy:
  provider: elasticbenastalk
  region: "us-east-1"
  app: "docker-java-app"
  env: "Dockerjavaapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-893382876075"
  bucket_path: "docker-java-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY