language: java
jdk: openjdk8

sudo: required

cache:
  directories:
    - .autoconf
    - $HOME/.m2

services:
  - docker

before_install:
  - chmod +x ./gradlew

script:
  # BUILD
  - ./gradlew build

  # GET NAME
  - PRJ_GROUP=$(gradle properties -q | grep "group:" | awk '{print $2}')
  - PRJ_NAME=$(gradle properties -q | grep "name:" | awk '{print $2}')
  - PRJ_VERSION=$(gradle properties -q | grep "version:" | awk '{print $2}')

  - echo "## PROJECT_GROUP - ${PRJ_GROUP}"
  - echo "## PROJECT_NAME - ${PRJ_NAME}"
  - echo "## PROJECT_VERSION - ${PRJ_VERSION}"

  - PRJ_JAR=${PRJ_NAME}-${PRJ_VERSION}.jar

  # DOCKER BUILD
  - docker build -t ${PRJ_GROUP}.${PRJ_NAME}:latest --build-arg JAR_FILE=build/libs/${PRJ_JAR} ./

deploy:
  provider: elasticbenastalk
  region: "us-east-1"
  app: "docker-java-app"
  env: "Dockerjavaapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-893382876075"
  bucket_path: "docker-java-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY